site_name: TerriaJS
#cosmo|cyborg|readthedocs|yeti|journal|bootstrap|readable|united|simplex|flatly|spacelab|amelia|cerulean|slate|mkdocs
#theme: readthedocs
theme:
    name: 'material'
    logo: 'terria.png'
docs_dir: 'doc'
site_dir: '../wwwroot/doc/guide'
markdown_extensions:
  - markdown.extensions.admonition
strict: true
pages:
- Home: 'README.md'
- Getting Started: 'getting-started.md'
- Customizing:
    - Overview: 'customizing/README.md'
    - Client-side Config: 'customizing/client-side-config.md'
    - Initialization Files: 'customizing/initialization-files.md'
    - Server-side Config: 'customizing/server-side-config.md'
    - Skinning: 'customizing/skinning.md'
- Connecting to Data:
    - Overview: 'connecting-to-data/README.md'
    - Cross-Origin Resource Sharing: 'connecting-to-data/cross-origin-resource-sharing.md'
    - Catalog Groups: 'connecting-to-data/catalog-groups.md'
    - Catalog Items: 'connecting-to-data/catalog-items.md'
    - Customizing Data Appearance:
        - Overview: 'connecting-to-data/customizing-data-appearance/overview.md'
        - Imagery Data: 'connecting-to-data/customizing-data-appearance/imagery-data.md'
        - Tabular Data: 'connecting-to-data/customizing-data-appearance/tabular-data.md'
        - Feature Information Template: 'connecting-to-data/customizing-data-appearance/feature-info-template.md'
    - Catalog Functions: 'connecting-to-data/catalog-functions.md'
    - Catalog Type Details:
        - ArcGIS MapServer (item): 'connecting-to-data/catalog-type-details/esri-mapServer.md'
        - Bing Maps (item): 'connecting-to-data/catalog-type-details/bing-maps.md'
        - Cesium 3D Tiles (item): 'connecting-to-data/catalog-type-details/3d-tiles.md'
        - Cesium Ion Imagery (item): 'connecting-to-data/catalog-type-details/ion-imagery.md'
        - Cesium Language (CZML) (item): 'connecting-to-data/catalog-type-details/czml.md'
        - Cesium Terrain (item): 'connecting-to-data/catalog-type-details/cesium-terrain.md'
        - Comma-Separated Values (CSV) (item): 'connecting-to-data/catalog-type-details/csv.md'
        - General Transit Feed Specification (item): 'connecting-to-data/catalog-type-details/gtfs.md'
        - GeoJSON (item): 'connecting-to-data/catalog-type-details/geojson.md'
        - GlTF (item): 'connecting-to-data/catalog-type-details/gltf.md'
        - Group (Manual) (group): 'connecting-to-data/catalog-type-details/group.md'
        - MAGDA Distribution (item): 'connecting-to-data/catalog-type-details/magda.md'
        - MAGDA (group): 'connecting-to-data/catalog-type-details/magda-group.md'
        - OpenStreetMap (item): 'connecting-to-data/catalog-type-details/open-street-map.md'
        - Web Map Service (WMS) (group): 'connecting-to-data/catalog-type-details/wms-group.md'
        - Web Map Service (WMS) (item): 'connecting-to-data/catalog-type-details/wms.md'
- Deploying:
    - Overview: 'deploying/README.md'
    - Deploying TerriaMap: 'deploying/deploying-terriamap.md'
    - Deploying to AWS: 'deploying/deploying-to-aws.md'
    - Deploying with Kubernetes: 'deploying/deploying-with-kubernetes.md'
    - Setting Up a Region Mapping Server: 'deploying/setting-up-a-region-mapping-server.md'
    - Setting Up Geoserver: 'deploying/setting-up-geoserver.md'
    - Using as a CKAN Previewer: 'deploying/using-as-a-ckan-previewer.md'
    - Controlling with URL Parameters: 'deploying/controlling-with-url-parameters.md'
    - Controlling in an &lt;iframe&gt; or Popup: 'deploying/controlling-in-an-iframe-or-popup.md'
- Contributing:
    - Overview: 'contributing/README.md'
    - Development Environment: 'contributing/development-environment.md'
    - Architecture: 'contributing/architecture.md'
    - Using a Custom Version of Cesium: 'contributing/using-a-custom-version-of-cesium.md'
    - Setting up Saucelabs: 'contributing/setting-up-saucelabs.md'
    - Problems and Solutions: 'contributing/problems-and-solutions.md'
- Acknowledgements:
    - Attributions: 'acknowledgements/attributions.md'
