terriamap:
    serverConfig:
        port: 3001
        allowProxyFor: [
            "nicta.com.au",
            "gov.au",
            "csiro.au",
            "arcgis.com",
            "argo.jcommops.org",
            "www.abc.net.au",
            "geoserver.aurin.org.au",
            "mapsengine.google.com",
            "s3-ap-southeast-2.amazonaws.com",
            "adelaidecitycouncil.com",
            "www.dptiapps.com.au",
            "geoserver-123.aodn.org.au",
            "geoserver.imos.org.au",
            "nci.org.au",
            "static.nationalmap.nicta.com.au",
            "githubusercontent.com",
            "gov",
            "gov.uk",
            "gov.nz",
            "sample.aero3dpro.com.au"
        ]
        initPaths:
        - "/etc/config/client"
        newShareUrlPrefix: "s"
        shareUrlPrefixes:
            s:
                service: "s3"
                region: "ap-southeast-2"
                bucket: "terriajs-ci-sharing"
                accessKeyId: "secret"
                secretAccessKey: "secret"
        feedback:
            userAgent: TerriaBot (TerriaJS Feedback)
            issuesUrl: https://api.github.com/repos/TerriaJS/demo-feedback/issues
            accessToken: secret
    clientConfig:
        initializationUrls:
        - simple
        parameters:
            bingMapsKey: "AiGfmTpmtbNIRJER8VKGKZMFZ4mGISCy4XS-Bvzb64IE3D0ILZpYorFHShd2AX8U"
            cesiumIonAccessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxZDY5MDE1YS0yNGFlLTQ1MzctYWNkNy0wNDQ1YWNiNTM5MDIiLCJpZCI6Mjk5Miwic2NvcGVzIjpbImFzciIsImdjIl0sImlhdCI6MTUzODAzMzgyNn0.a2uTotdiHUo8FiHsO4MVNZ1KT5pOF0rb7CFdwbRAsOo"
            googleAnalyticsKey:
            disclaimer:
                text: "Disclaimer: This map must not be used for navigation or precise spatial analysis"
                url: "https://terria.io"
            developerAttribution:
                text: "Terria"
                link: "https://terria.io"
            appName: "TerriaJS Continuous Integration"
            brandBarElements: ["", "<a target=\"_blank\" href=\"http://terria.io\"><img src=\"images/terria_logo.png\" height=\"52\" title=\"Version: {{version}}\" /></a>", ""]
            supportEmail: "info@terria.io"
            mobileDefaultViewerMode: "2d"
            experimentalFeatures: true
            feedbackUrl: "feedback"
            helpContent: 
                - 
                  itemName: gettingstarted
                  title: Getting Started
                  markdownText: "# Getting started with the map\n\nTemporarily removed until CI issues resolved"
                  icon: "video"
                  videoUrl: "https://www.youtube.com/embed/NTtSM70rIvI"
                  placeholderImage: "https://img.youtube.com/vi/NTtSM70rIvI/maxresdefault.jpg"
                -
                  title: Step by step guide
                  itemName: stepbystepguide
                  paneMode: trainer
                  icon: "oneTwoThree"
                  markdownText: "# Step by step guide\n\nLaunch a step by step guide for various popular workflows below:"
                  trainerItems:
                  - 
                    title: Adding satellite imagery
                    steps:
                      - title: Open the data catalogue by clicking Explore map data
                        description: You''ll find a button named "Explore map data" on your left hand menu
                      - title: Navigate to some satellite data on the left hand side of the data catalog
                        description: Select the satellite catalog item of interest
                      - title: Click Add to the map
                        description: Alternatively, you can click the Plus button to the right of your
                          catalog item of interest
                      - title: Adjust zoom level to suit
                        description: You may need to adjust your zoom level to see the scope of the satellite
                          imagery for the given date [...]
                  - 
                    title: Adding data to the map
                    steps:
                      - title: Open the data catalogue by clicking Explore map data
                        description: You''ll find a button named "Explore map data" on your left hand menu
                      - title: Select a catalogue item of interest
                        description: Navigate around the catalogue until you find some data of interest.
                  - 
                    title: Change detection
                    steps:
                    - title: Placeholder
                      description: Placeholder
                  - 
                    title: Compare 2 dates
                    steps:
                    - title: Placeholder
                      description: Placeholder
    resources:
        requests:
            cpu: 10m
            memory: 10Mi
