terriamap:
    serverConfig:
        port: 3001
        allowProxyFor: [
            "nicta.com.au",
            "gov.au",
            "csiro.au",
            "arcgis.com",
            "argo.jcommops.org",
            "www.abc.net.au",
            "geoserver.aurin.org.au",
            "mapsengine.google.com",
            "s3-ap-southeast-2.amazonaws.com",
            "adelaidecitycouncil.com",
            "www.dptiapps.com.au",
            "geoserver-123.aodn.org.au",
            "geoserver.imos.org.au",
            "nci.org.au",
            "static.nationalmap.nicta.com.au",
            "githubusercontent.com",
            "gov",
            "gov.uk",
            "gov.nz",
            "sample.aero3dpro.com.au"
        ]
        initPaths:
        - "/etc/config/client"
        newShareUrlPrefix: "s"
        shareUrlPrefixes:
            s:
                service: "s3"
                region: "ap-southeast-2"
                bucket: "terriajs-ci-sharing"
                accessKeyId: "secret"
                secretAccessKey: "secret"
        feedback:
            userAgent: TerriaBot (TerriaJS Feedback)
            issuesUrl: https://api.github.com/repos/TerriaJS/demo-feedback/issues
            accessToken: secret
    clientConfig:
        initializationUrls:
        - simple
        parameters:
            bingMapsKey: "AiGfmTpmtbNIRJER8VKGKZMFZ4mGISCy4XS-Bvzb64IE3D0ILZpYorFHShd2AX8U"
            cesiumIonAccessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxZDY5MDE1YS0yNGFlLTQ1MzctYWNkNy0wNDQ1YWNiNTM5MDIiLCJpZCI6Mjk5Miwic2NvcGVzIjpbImFzciIsImdjIl0sImlhdCI6MTUzODAzMzgyNn0.a2uTotdiHUo8FiHsO4MVNZ1KT5pOF0rb7CFdwbRAsOo"
            googleAnalyticsKey:
            disclaimer:
                text: "Disclaimer: This map must not be used for navigation or precise spatial analysis"
                url: "https://terria.io"
            developerAttribution:
                text: "Terria"
                link: "https://terria.io"
            appName: "TerriaJS Continuous Integration"
            brandBarElements: ["", "<a target=\"_blank\" href=\"http://terria.io\"><img src=\"images/terria_logo.png\" height=\"52\" title=\"Version: {{version}}\" /></a>", ""]
            supportEmail: "info@terria.io"
            mobileDefaultViewerMode: "2d"
            experimentalFeatures: true
            feedbackUrl: "feedback"
            helpContent: 
                - 
                  itemName: gettingstarted
                  title: Getting Started
                  markdownText: "# Getting started with the map\n\nTemporarily removed until CI issues resolved"
                  icon: "video"
                  videoUrl: "https://www.youtube.com/embed/NTtSM70rIvI"
                  placeholderImage: "https://img.youtube.com/vi/NTtSM70rIvI/maxresdefault.jpg"
                -
                  title: Step by step guide
                  itemName: stepbystepguide
                  paneMode: trainer
                  icon: "oneTwoThree"
                  markdownText: "# Step by step guide\n\nLaunch a step by step guide for various popular workflows below:"
                  trainerItems:
                  -
                    title: Adding satellite imagery
                    footnote: "Important: Satellite imagery can take a little while to load so please be patient. If images don’t seem to be loading, zoom out a little bit"
                    steps:
                    - title: Find a location to view satellite imagery
                      markdownDescription: "- Use the location search or zoom and pan around the map using your mouse or the zoom controls"
                    - title: Find satellite images in the data catalogue using "Add Data" button
                      markdownDescription: "- Click \"Explore map data\" and navigate to Satellite images and press \"Add Data\"\n- Select your satellite option: Landsat or Sentinel, what resolution and daily or composite images. This can depend on resolution of the image you need (10m or 25m) and whether you want daily, 16 day composite, or annual average images"
                    - title: Filter images to find satellite imagery
                      markdownDescription: "- Filter images by location to quickly find satellite images for that location\n- Satellites circle the globe many times a day. You can expect satellite imagery to be available for one location every two weeks\n- If you haven''t already selected your point of interest on the map, zoom in to select one. You will see the filter applied in blue in the Workbench on the left"
                    - title: Select a time and date
                      markdownDescription: "- Use the date picker to select a time and date. Cycle backwards through previous years using the back arrow\n- Choose another date if your imagery is obscured by cloud. You can quickly cycle back and forward using the arrows next to the date picker"
                  -
                    title: Adding data to the map
                    steps:
                    - title: Open the data catalogue by clicking Explore map data
                      markdownDescription: "You''ll find a button named \"Explore map data\" on your left hand menu"
                    - title: Select a catalogue item of interest
                      markdownDescription: Navigate around the catalogue until you find some data of interest.
                  -
                    title: Change detection
                    steps:
                    - title: Placeholder
                      markdownDescription: Placeholder
                  -
                    title: Compare 2 dates
                    steps:
                    - title: Placeholder
                      markdownDescription: Placeholder
    resources:
        requests:
            cpu: 10m
            memory: 10Mi
